spring:
  profiles:
    include: secret
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          naver:
            scope:
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: '${base.url}/{action}/oauth2/code/{registrationId}'
          kakao:
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${base.url}/{action}/oauth2/code/{registrationId}'
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    hibernate:
      ddl-auto: create-drop

base:
  url: 'http://localhost:8080'